[app]

timeout = 720
database_uri = "mysql+pymysql://lw:lw@lw-db/stock"
sleep = 5

[hyper_sage]
uri = "https://157.231.105.106:40027"
api_key = "ngEXJVHb4mHYvr2tuNTsjBNz"
timeout = 30

[adjustments]
adjustments_uri = "/api/stock"

[email]
maximum_errors = 3
sender_email = "info@lewisandwood.co.uk"
receiver_email = "djs1602@gmail.com"
subject = "StockSys Alert"
postmarker_token = "f8049f6f-dec7-49b0-bf1f-cc10119cd916"

[sage]
stock_uri = "http://lwsageserver:5495/sdata/accounts50/GCRM/%7B158156F0-396C-4FA9-AD17-F4A27F82A47D%7D/commodities"
stock_levels = "?select=reference,name,inStock,allocated,freestock,onOrder,salesPrice&format=json&where=reference in "
password = ""
user = "Helen"
#sage timeout
timeout = 20
get_cost_price = false
