[app]

# timeout in  minutes
timeout = 720
database_uri = "mysql+pymysql://lw:lw@localhost/stock"
sleep = 120

[hyper_sage]
uri = "https://hyperdrive.hyperext.com:27013"
api_key = "hwytrwqvf262vsz9"
timeout = 45

[adjustments]
adjustments_uri = "/api/stock"
